name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Get current moonlight-embedded version number
        id: moonlight-version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: moonlight-stream/moonlight-embedded       
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm/v7
          push: true
          tags: clarkemw/moonlight-embedded-raspbian:latest, clarkemw/moonlight-embedded-raspbian:${{ steps.moonlight-version.outputs.release }}